// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCn_1ZRNPvqgOZwQiLlkV7Tn44puXaFs',
    appId: '1:1074006350096:web:622841de484bbfebb22d95',
    messagingSenderId: '1074006350096',
    projectId: 'minesvilleposinventory',
    authDomain: 'minesvilleposinventory.firebaseapp.com',
    storageBucket: 'minesvilleposinventory.firebasestorage.app',
    measurementId: 'G-LZL05CMT59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8kbaeW0YcR9POXabjNnKqnVHDvE2QG4s',
    appId: '1:1074006350096:android:3efd5ee973e5f90fb22d95',
    messagingSenderId: '1074006350096',
    projectId: 'minesvilleposinventory',
    storageBucket: 'minesvilleposinventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWk8w4kvLFD7YnDEQ0Y9R0LW7cYD2-1sE',
    appId: '1:1074006350096:ios:afef5d7d3e12481bb22d95',
    messagingSenderId: '1074006350096',
    projectId: 'minesvilleposinventory',
    storageBucket: 'minesvilleposinventory.firebasestorage.app',
    iosBundleId: 'com.example.posInventoryApp',
  );
}
